### ISSUE TITLE
Able to specify image `platform` when creating `ch` shell

### ISSUE THREAD

**Issue by camerondurham** [camerondurham/ch#48]
**Is your feature request related to a problem? Please describe.**
- camerondurham/cs350-docker commands fail (appears to be on any non-linux/amd64 arch system), see:
    - #47
    - https://github.com/camerondurham/cs350-docker/issues/15 

**Describe the solution you'd like**

`ch` should offer specifying the image platform you want to run with a `platform` flag.

This issue covers the feature required to create a shell env and specify the platform, but the cs350-docker repo needs to have documentation updated too.

**Comment by a-harhar** [comment]
@camerondurham I've been working on this locally, fairly certain I figured out how to do it. I'll make the PR for it shortly!

**Comment by a-harhar** [comment]
@camerondurham created PR for adding the flag #49. Please leave any suggestions that you have on coding style and I can make the updates! Also not entirely sure if I updated all the places for documentation (I updated README but that was it). Hope this helps!
